environment:
  my_variable:
    secure: FasVD1zterdr+ACRzjufOBSTVrPUj5lfaKNpdRia+P3GcfUvOxZdtyTabHFnISg/a6w5FCS5E7RAFdIrs1b+zMMHdidiCP0Sj1k2yC/TNa4wqwKkLFmRXar31bJjSsxTMQn0ft3+EW0HZCBcN1BDK4dRuDgy/41Jaglk7e9VYQS7NYJcFJB2zJi0+w6rO6FVHWBZDafvmP3DmhqmIcPMwClK537QCNitw06AdI377oGVu33IGJ/OdhMIU7LOynZJAC74eR0TNE8RVVUtZyp3d5sr35JbPxJDA7Af1X8jx2PJw24X+AtMKMx8CUAKYt/5H+kKfC5cH/osCbjferIAMKBtKUIYJMxpraR3wvT7iF21WFsWxFVMOk0Osa8Hcs/WRqGeewCfxMu4i+Mup7QYV5ugzkQsDe2TsVQ49BzDk15SLGImFBkD71JM5R+s9TKICAU6+qVgZw2pwI4hFUYryFOG1uA6ksZGJh5IQqRr4bA5C7/wejVm1SKwonQUCMujAGqbUC/tZcCZuSRPs28noW593kT64juw+grQyrXjpgsfxTKXInIJk1zDt5jhLxU0LT165P6eMxMhnyhG+X1Id71Ta/gi1uxsepUacA/z+gXws+Arqqh69JFyAXBqvHRZ976h1PVpuBrkrHI84Wwb0SMFeriq+gqUpFGzOvt/EMMMNW/O6MonXNnMft/3W4MV6B15y+Xgo+Ap1+W6yz5iwb7W/exH8hOqDkm/unSKWdtb1CQTaYWI/Ut4WEBC05zlE8ekf2WX9wBlPu+uudbVxvKZ0PGJTazGta+i1k4DxhGxjfiShFvzVq88hPSWuGRRXXPRCslyw5nX2gdMdVyWYwv5RyK0GGOfbKoPrMHbgQDyQzuUgwuCdtW5sNF2cD9EuwL+gByH5+uLmYjzCzXW/7Z3OxG2Pn1lEnZPuBV1clOnBtVq81bBuW20+6UPSbxuaqkmBXZCMB/NlFhLOovtb1tIC/miu70Z9ca0opoSjWSzAoisL2+kp/sbh5pmU5+oeAQBVZ97UcKwTRy55dd7oWQRzhtTXu0MbsIjIzGb9sB0/V1lbVtJk2aNBw3ds0QB3cv/Ro/Utn7LUI5fiJyodLql4m9ttwU2kCKZHNzeB/nrYa+gp1FIai24Mee57dVKoyPVV/u86IxFM5CM6ObLuJabF49J63L4e/DFwoAnSvqRyhp3zFCWBKqFG++gYpkeDhfk8XRDAhgIN9+WUrjq6gGgBd0kEctRS6zp/cxCAbtE6rIVvRJnz9nFEPmnEAUHFhWEZzUGGj9FbiajvnRUykpfefvVmaJnJUaijeR3nOjP/GFsLWu5w4uPXrMiFYuvtuQAPXGH85mJvOKRk0fk7bZlJ384YSZm0RNn8Lb5F7QRFdHDyMCDSBhZ3l3ZsBJZenvQyYJO8eZB6K2MgoM8XZxB2n4ZK4aFwm5CqBEaYjbL0W8JlisyPxkHS8MPUjzoS+LFo1HVm/y2iW+IuRJIaMTq5GugjpT7+UeU6Zs+8UMZ7gZUQz8amIklTAFRp691SCBMOAjjM6WQTheKC4c6rOihoZc0oCqOS3CPOluxJJwajGkIr7P58Mqn/aqHyXGGypwT1STwYbcp2w5fvEoWQy+BBNELBkPgnKHaFHFZupdb7MMVNfPzO5VjxMNUN2EGekK21ksxjhNbvZHdHACOTK8gx6fGFBd6zI0ftJ7ht2b/uYJNyHIIXy6DKIxzZstiUTGnbo25ZJ94A+EX5UEGbvE8I+KXVePRuLfbO7mMq4mLzYOiWuRWVETh03mSU76GrAct/8ZJ/HjB3zorD5p/GMy1FHosDT9hZL2bp3On9oHxAx2/3ngC+kVyARYoli2MShSH12IlYVws20guolMeRdi1BW9qq6ZxcYTN1mHZe7hDXLNM5Wxhwch7WnJtLMaLRAAo4hM0WeXdU3BEIrZasQ2FJQiaPWbmA0FDNo1mocHxf3s7F5/0kDM32eqG5ypUm+X9f3Wr6U0qpHyKhhbmFj5iGtvyTSGCwO564NVGiz0kzzo8rRASvxOewkOsw+UpOTxW8ynUlws3fpIxT4F0ksDY1lONE1f59HljyRbYG/WkjHyTQg5HZi8mC53IIlOGPULfyMfrYQnJt5GAswGzlJfTri2nBYwVQVJ711qoZBhoVk6HbRzUYNlwHKKHPtlLyaEZzb+7QlL6MDHaRhdeG/BstA4dsFFGkukX4Vdqd7Zz9Rk4JubCwEe2m+9NtAWLhhZearjG9PqJEhASSgnE61KB7ZupGP9Xd2tO4Phyt1GBYc9MuxP0q2RCvBS3RFvCu5rv/Om4CXypgye95y8PJ9bD4rDdaoTluddQTkUDriQOP6dKWtNG7ETMpKhCylxj63wbBW7OObIW8cXjAWJojb1IUDPabpxArZbCbHzPqYhLEzrwkFcxC3VoxZlVLUzT5qTzEa468xuKLsWIfRZu6NnM57b+XyyjeUuxEE/6uqytpNnt8HilCJ5D55g43u6zatsJ4u2NDBcrQfMFHD+rMoqDjuENzxwfpqsZFSyO7WjVdF1QcOSjPtbwbmASjPGyyZTI6GaFUsm52YPqX9lJXWr8774ppywED7HAWebPxorzWroSQTdbdBa6ksG0RMMzMZqdPEcRy8iZa3zfcn3JY8pqvPAMiS3RK7vgrku3SzeDKZghCNUM8POjadlYBzsRVnG4h5H9egBorP7MgZReSXhdePLCpffr8oSNb5Cp4Rfx3Qapw/iMdt9DPifm34w8tcexKYfYIYi70s0VsL3JJNqY+O6nvuAI9Qrun+sS09cCQJN8T5hpUUmkvhehKtutcuVHL+PkNmo5ncmOJVXrpy+91jBK8ml5lDu35pGfJdN0fjspXSnFiYzBrypJJ+H1VxGHmntDnXaQ2+40yF5jzNJuZCnrDpdHNA/T6ViV5wQG6L3wdFPnGBEgnLzSEVshelO/EFazpKBnpStVVczYvzFWdH9N9A/xSU28plr5iHKJIFs/kFEKhSLkICnBoRuYASYxi+8YQodUJaQ6qkYjMOz+tPtWjlCw1lwNamlpWtSevJekKeBvZnWWWmi9vU1i/Di90mUmo20k9Ri91PRUk2Yf9I99WujcaScuaq6YYCK8DqepFEuYcXu6U6+BE6ls7k3HHa8Pn5EZvBbR/4PitHppUUZcsbpJf0ojRXgkx9FHCCfledvlSrwSyX56wHPkCg5Iq/Z/Sn7EcTt+LotpqRkGX27DSNil7nh9KxZcT5H1reoxxvrACk5E56m9vpMhkEzzTBu7Dyl9ag1IFceRc6Ig2j0NcWxh2GLXVaevHucjzyOD67RPGnuIdoC7/ojnro3itdR/IerG4vuG85LggwW3Xvw4fr51wTVUnEO+oW1gjmWi6cIqQcvD+VZCatlyKaXAxtkmd3VBNPoQEz+/0OGJUw/B8fayYGlQjUoTy4jPkzxd3TvX557KdGgsKdTcuvDnrrHFjt6r+xPco/G6YK8OutdOLjnVupPjEeKRPnuIUNBDIVp3+lnd6ncY3Q5q8+oOQzgz5TzkGEqqGPYPeoHNTomhSLsR3IFB5Ylma3Mjqtv5IVOveEoiO7H09TD07xTE429DElZPgG5d0Uatzm13pjfkggriArPYCYcRvVJ8lMW0gSbIcvII/Pa7P2vMSe2MpaOxoySshv8hN+EHBishV+dgKFITqo8hT723IsdaDA+MWEsRr5+iVJq5V9xWdNbx8rPdCQD/mova8H9JpLivoC15FzC6tFx7bRmb4U0JcgGIG+py2ow49by9TMN2kZpI0zQPvjJ2r7iUzt5BXOG9dpThVEkURFIQ4TY8ND0=

artifacts:

- path: gisticon.io

  name: 4gisticon@gisticon.github.io

before_deploy:

- sh: ''

deploy:

- provider: WebDeploy

  server: gisticon.io

  website: gisticon.io

  username: gisticon.io

  password:

    secure: W/Q0tLbUX++xUixhkRP2qA==

  artifact: gisticon.io

  aspnet_core: true

  ntlm: true

  remove_files: true

  app_offline: true

  do_not_use_checksum: true

  aspnet_core_force_restart: true

  on:

    branch: gh-page

    4gisticon@gisticon.github.io: .github

- provider: Environment

  name: 4gisticon@gisticon.github.io

  on:

    branch: gh-page

    .github: .github

- provider: Local

  4gisticon@gisticon.github.io: .github

  assembly_version: '{version}'

  file_version: '{version}'

  informational_version: '{version}'

environment:

  $ git clone: '*******'

  project.git: '*******'

  matrix:

  - git: '*******'

  - {}

  - {}

services:

- mssql2017

- mysql

hosts:

  kixeye.com: 54.148.45.119

install:

- cmd: $ git clone user@git.example.com:/srv/git/my_project.git

nuget:

  project_feed: true

  disable_publish_on_pr: true

  disable_publish_octopus: true

before_build:

- cmd: "test .git Conflicting files .git[https://github.com/GistIcon/pret/pull/16/conflicts]\ntest .git var swf/end_=_.swift \ntest .git var swf/java./tab.js \ntest .git var xml./surebugnotme.xml"

build:

  publish_wap: true

  publish_azure: true

  publish_nuget: true

  publish_nuget_symbols: true

  include_nuget_references: true

  publish_aspnet_core: true

  publish_core_console: true

  parallel: true

  verbosity: minimal

before_package:

- cmd: "test .git Conflicting files .git[https://github.com/GistIcon/pret/pull/16/conflicts]\ntest .git var swf/end_=_.swift \ntest .git var swf/java./tab.js \ntest .git var xml./surebugnotme.xml"

after_build:

- cmd: "test .git Conflicting files .git[https://github.com/GistIcon/pret/pull/16/conflicts]\ntest .git var swf/end_=_.swift \ntest .git var swf/java./tab.js \ntest .git var xml./surebugnotme.xml"

artifacts:

- path: pret

  name: pret

before_deploy:

- pwsh: >-

    $ ssh user@git.example.com



    $ cd /srv/git/my_project.git



    $ git init --bare --shared

deploy:

- provider: Webhook

  url: https://github.com/GistIcon/pret/settings/hooks/54354783

  authorization:

    secure: kQaolyMV6oTHESm1TrFpDQ==

  request_timeout: 1

  on:

    branch: master

    pret: '******'

- provider: NuGet

  api_key:

    secure: 8wV9U2DcPnH3tBbbyB2OhCNMipJCVynuRwr5J5Wj2Fc=

  skip_symbols: true

  on:

    branch: master

    project feed: '******'

after_deploy:

- pwsh: $ git clone user@git.example.com:/srv/git/my_project.git

notifications:

- provider: Webhook

  url: https://github.com/GistIcon/pret/settings/hooks/76124641

  method: POST

  on_build_success: true

  on_build_failure: true

  on_build_status_changed: true

on_success:

- cmd: ''
