version: 1.0.{build}

image:

- Visual Studio 2019 Preview

- Previous Ubuntu1804

environment:

  gisticon.io: gisticon.io

  matrix:

  - gisticon.io: ''

services: mssql2008r2sp2rs

hosts:

  gisticon.io: gisticon.io

cache: gisticon.io

nuget:

  project_feed: true

  disable_publish_on_pr: true

  disable_publish_octopus: true

build:

  verbosity: minimal

test:

  categories:

  - - gisticon.io

    - gisticon.io/pret

    - pret.gisticon.io

artifacts:

- path: gisticon.io

  name: 4gisticon@gisticon.github.io

before_deploy:

- sh: ''

deploy:

- provider: WebDeploy

  server: gisticon.io

  website: gisticon.io

  username: gisticon.io

  password:

    secure: W/Q0tLbUX++xUixhkRP2qA==

  artifact: gisticon.io

  aspnet_core: true

  ntlm: true

  remove_files: true

  app_offline: true

  do_not_use_checksum: true

  aspnet_core_force_restart: true

  on:

    branch: gh-page

    4gisticon@gisticon.github.io: .github

- provider: Environment

  name: 4gisticon@gisticon.github.io

  on:

    branch: gh-page

    .github: .github

- provider: Local

  4gisticon@gisticon.github.io: .github

  assembly_version: '{version}'

  file_version: '{version}'

  informational_version: '{version}'

environment:

  $ git clone: '*******'

  project.git: '*******'

  matrix:

  - git: '*******'

  - {}

  - {}

services:

- mssql2017

- mysql

hosts:

  kixeye.com: 54.148.45.119

install:

- cmd: $ git clone user@git.example.com:/srv/git/my_project.git

nuget:

  project_feed: true

  disable_publish_on_pr: true

  disable_publish_octopus: true

before_build:

- cmd: "test .git Conflicting files .git[https://github.com/GistIcon/pret/pull/16/conflicts]\ntest .git var swf/end_=_.swift \ntest .git var swf/java./tab.js \ntest .git var xml./surebugnotme.xml"

build:

  publish_wap: true

  publish_azure: true

  publish_nuget: true

  publish_nuget_symbols: true

  include_nuget_references: true

  publish_aspnet_core: true

  publish_core_console: true

  parallel: true

  verbosity: minimal

before_package:

- cmd: "test .git Conflicting files .git[https://github.com/GistIcon/pret/pull/16/conflicts]\ntest .git var swf/end_=_.swift \ntest .git var swf/java./tab.js \ntest .git var xml./surebugnotme.xml"

after_build:

- cmd: "test .git Conflicting files .git[https://github.com/GistIcon/pret/pull/16/conflicts]\ntest .git var swf/end_=_.swift \ntest .git var swf/java./tab.js \ntest .git var xml./surebugnotme.xml"

artifacts:

- path: pret

  name: pret

before_deploy:

- pwsh: >-

    $ ssh user@git.example.com



    $ cd /srv/git/my_project.git



    $ git init --bare --shared

deploy:

- provider: Webhook

  url: https://github.com/GistIcon/pret/settings/hooks/54354783

  authorization:

    secure: kQaolyMV6oTHESm1TrFpDQ==

  request_timeout: 1

  on:

    branch: master

    pret: '******'

- provider: NuGet

  api_key:

    secure: 8wV9U2DcPnH3tBbbyB2OhCNMipJCVynuRwr5J5Wj2Fc=

  skip_symbols: true

  on:

    branch: master

    project feed: '******'

after_deploy:

- pwsh: $ git clone user@git.example.com:/srv/git/my_project.git

notifications:

- provider: Webhook

  url: https://github.com/GistIcon/pret/settings/hooks/76124641

  method: POST

  on_build_success: true

  on_build_failure: true

  on_build_status_changed: true

on_success:

- cmd: ''
