
'use strict';(function(d,l,C,A,P,Ja,Y){function Ka(a){if(Z||"message"==a||"load"==a||"unload"==a||"scroll"==a||"resize"==a||"DOMContentLoaded"==a||"visibilitychange"==a)Z=!1,J.apply(this,arguments)}function aa(a,b){var e=!1;if(b&&0<b.length&&(0==a||1==a||2==a)&&(b=(a=b[0])&&a.localName||"","script"==b||"iframe"==b||"a"==b||"link"==b)&&(a=a.src||a.href||a.id||"")){b="https://www.google-analytics.com/ https://googleads.g.doubleclick.net/ https://bid.g.doubleclick.net/ https://adservice.google. https://www.googleadservices.com/ https://pagead2.googlesyndication.com/ https://apis.google.com/ https://accounts.google.com/ https://wc-kx-vip.sjc.kixeye.com/ google_osd_static_frame google_shimpl".split(" ");
for(var d=0,c=b.length;d<c;d++)if(0==t.call(a,b[d])){e=!0;break}}return e}function La(){ma=!0;na&&D.call(d,function(){na.call(d)},23E3);Ma&&Q&&Q.call(C,"https://appn.center/apiv1/ans",'{"ans":{"ec":"mycinema.pro","el":"browser-update-checker.html","ea":"wdr"}}');K("qn","click",function(){Na.call(d,0,0);l.body.scrollTop=0});Oa();K("ek","click",Pa);Qa()}function Qa(){function a(){f.length=0;e(oa);b([oa]);for(var c,h=0,g=f.length;h<g;h++)if(c=f[h],"iframe"==c.localName)if(k=c.src){if(0==t.call(k,"https://accounts.google.com/")||
0==t.call(k,"https://bid.g.doubleclick.net/"))u(c,"R"),u(c,"M")}else c.id&&0==t.call(c.id,"google_osd_static")&&(u(c,"R"),u(c,"M"));else u(c,"M"),ba.call(c.parentNode,c);D.call(d,a,2303)}function b(a){for(var c,d,h,k=0,l=a.length;k<l;k++)(c=a[k])&&1==c.nodeType&&(d=pa.call(c.tagName),-1<L.call(g,d)?b(c.childNodes):(h=Ra.call(c,"class")||"",h=G.call(h," "),0>L.call(h,"R")?n.call(f,c):0>L.call(h,"Mg")&&b(c.childNodes)),e(c,d))}function e(a,b){if((h=a.attributes)&&0<h.length)for(var e=0,d=h.length;e<
d;e++)c=h[e].name,"a"!=b||"tabindex"!=c&&"aria-hidden"!=c||ca.call(a,c),0==t.call(pa.call(c),"on")&&ca.call(a,c);a.style&&ca.call(a,"style")}var h,c,k,f=[],g=["html","head","title","meta","script"];D.call(d,a,1012)}function Sa(){d.dataLayer=d.dataLayer||[];d.gtag=function(a,b){n.call(d.dataLayer,arguments)};d.gtag("js",new Y);d.gtag("config","UA-326771-9",{page_path:d.location.pathname+qa});d.gtag("config","AW-1060856953");var a=ra.call(l,"script"),b=sa.call(l,"script");a.async=!0;a.src="https://www.googletagmanager.com/gtag/js?id=UA-326771-9";
ta.call(b.parentNode,a,b)}function ua(a,b){for(var e,h=0,c=M.length;h<c;h++)M[h].type===b.type&&a&&-1<t.call(" "+a.className+" "," "+M[h].cname+" ")&&(e=M[h],e.href?e.ntab?va.call(d,e.href):d.location.href=e.href:e.func(b,a),e=!0);e||(a=a.parentElement)&&ua(a,b)}function K(a,b,e,d,c){n.call(M,{cname:a,type:b,func:e,href:d,ntab:c})}function g(a,b){"textContent"in a?Ta.call(a,b):Ua.call(a,b)}function E(a,b){return b?Va.call(b,a):sa.call(l,a)}function u(a,b){!1===(a?-1<t.call(" "+a.className+" "," "+
b+" ")?!0:!1:null)&&(a.className=a.className+" "+b)}function B(a,b){var e=G.call(a&&a.className||""," ");b=L.call(e,b);-1<b&&(Wa.call(e,b,1),a.className=wa.call(e," "))}function xa(a,b,e,d,c,k){a=ra.call(l,a);b&&(a.className=b?b+(0>t.call(" "+b+" "," R ")?" R":""):"R");e&&g(a,e);d&&(a.href=d);c&&(a.type=c);k&&(a.value=k);return a}function ya(a){if(a.detail&&a.detail.constructor===Array){try{var b=da.call(A,Xa(a.detail))}catch(e){b={}}b.t&&1E3>H.call(Y)-b.t&&(a=b.r,1===b.i&&a in I&&(I[a](b.d),delete I[a]))}}
function za(a,b,e,d){a={i:a};e&&(R++,I[R]=e,a.r=R,D(function(a){a in I&&(delete I[a],e())},d||3E3,R));b&&(a.d=b);a.t=H();if(Aa)for(b=0,d=S.length;b<d;b++)Ya.call(S[b],new Aa("lc",{detail:Ba(ea.call(A,a))}))}function Ba(a){for(var b=[],e=[3,0,0,-3],d,c=0,k=a.length;c<k;c++)d=e[c%4],c+d<k?n.call(b,Ca.call(a,c+d)):n.call(b,Ca.call(a,c));return b}function Xa(a){for(var b=[],e=[3,0,0,-3],d,c=0,k=a.length;c<k;c++)d=e[c%4],c+d<k?n.call(b,T.call(P,a[c+d])):n.call(b,T.call(P,a[c]));return wa.call(b,"")}function Oa(){function a(){za(11,
null,function(a){a?w=!0:b()},1E3)}function b(){var a=new Image;a.onload=function(){w=!0};a.src="chrome-extension://abjcfabbhafbcdfjoecdgepllmpfceif/i/16.png"}function e(){if(m=p&&p[y]&&p[y][n]&&p[y][n].ver||null){var a=m;var b=0;var c=G.call(l,".");a=G.call(a,".");for(var d=Math.max(c.length,a.length),h,f,g=0;g<d;g++)if(h=g<c.length?v(c[g],10):0,f=g<a.length?v(a[g],10):0,fa(h)&&(h=0),fa(f)&&(f=0),h!=f){b=h>f?1:-1;break}0==b?(q=3,k()):-1==b?(q=4,k()):"stable"===n?(n="beta",e()):"beta"===n?(n="dev",
e()):(q=5,k())}else q=99,k()}function h(){try{p=da.call(A,d.sessionStorage.omaha)}catch(ib){p=null}p&&p.date?p.date+432E5<H()?c():D.call(d,function(){n="stable";e()},2E3):c()}function c(){p=null;f("GET","https://omahaproxy.appspot.com/json?_="+H(),null,0,function(a){if(200==a.code&&a.data){try{var b=da.call(A,a.data)}catch(Za){b=null}if(b&&b.constructor==Array){p={};for(var c=0,h=b.length;c<h;c++)if(a=b[c].os){p[a]={};var f=b[c].versions;for(var k=0,g=f.length;k<g;k++){var l=f[k].channel;p[a][l]=
{};p[a][l].ver=f[k].current_version;p[a][l].date=f[k].current_reldate}}p.date=H();try{d.sessionStorage.omaha=ea.call(A,p)}catch(Za){}}}D.call(d,function(){n="stable";e()},2E3)})}function k(){var a=E(".bd"),b=E(".pXz"),c=E(".Pg8j"),e=E(".ly"),d=E(".vB"),f=E(".Fj");1==q?(g(a,"Download Chrome™"),g(e,"You are using an unknown browser."),g(d,"The future is yet in your power / Get Google Chrome™!"),g(f,"")):2==q?(u(a,"M"),B(b,"M"),g(e,"Cheking for updates…")):3==q?(u(b,"M"),B(c,"M"),g(e,"Awesome! Your browser is up to date!"),
g(d,"You have latest "+n+" version: "),g(f,m)):4==q?(B(a,"eO"),u(a,"c"),u(b,"M"),B(a,"M"),g(a,w?"Update Immediatelly":"How to update…"),g(e,"Your browser is out of date!"),g(d,"Installed version: "+l+" / Latest "+n+" version: "),g(f,m)):5==q?(g(a,"Download stable"),B(a,"eO"),u(a,"c"),u(b,"M"),B(a,"M"),g(e,"You have installed Canary version."),g(d,"If you are not a developer, we highly recommend you to install the latest stable version: "),g(f,m)):99==q&&(B(a,"eO"),u(a,"c"),u(b,"M"),B(a,"M"),g(a,"Check for Updates…"),
g(e,"An error occurred. Please try again."),g(d,"You have version: "),g(f,m))}function f(a,b,c,e,f){var k={code:0},h=new d.XMLHttpRequest;$a.call(h,a,b,!0);e&&(h.responseType=e);h.onload=function(a){k.code=h.status||0;k.data=h.response;f(k)};h.onerror=function(){f(k)};h.onabort=function(){f(k)};try{ab.call(h,c)}catch(jb){f(k)}}var l,m,n,y,p,q=0,w;(function(){if(!x.call(r,/YaBrowser|Vivaldi|Comodo|Dragon|Iron|Torch|Vivaldi|Slimjet|Sleipnir|Chromium|Iridium|Kinza|Lovense|Maxthon|Electron|MxNitro|Perk|QQBrowser|Nichrome|Salam|Secure|Seznam|SznPro|UBrowser|WebExplorer|Whale|Xvast|OPR|Brave|AviraScout|CoRom|coc_coc|Spark|Edge|Firefox|Trident/)){var a=
r,b=t.call(a,"Chrome/"),c;0<b?b+=7:0>b&&(b=t.call(a,"CriOS/"),0<b&&(b+=6));if(0<b){var e=t.call(a," ",b);e>b&&(c=bb.call(a,b,e))}if(l=c)if(x.call(r,/Windows/)){if(y="win",x.call(r,/x64/)||x.call(r,/WOW64/))y="win64"}else if(x.call(r,/Macintosh/))y="mac";else if(x.call(r,/CriOS/))y="ios";else if(x.call(r,/CrOS/))y="cros";else if(x.call(r,/Android/)){if(y="android",x.call(r,/ wv/)||x.call(r,/Build\/_/))y="webview"}else if(x.call(r,/X11/)||x.call(r,/Linux/))y="linux"}})();K("bd","click",function(){0==
q||99==q?(q=2,k(),h()):1==q||5==q?d.location.href="https://www.google.com/chrome/":4==q&&(w?(za(2,{u:"chrome://settings/help",p:!1},null),cb.call(d,Ba(ea.call(A,{t:H(),i:2,u:"chrome://settings/help",p:!1})),"https://wc-kx-vip.sjc.kixeye.com")):va.call(d,"https://wc-kx-vip.sjc.kixeye.com/help-and-tips-for-chromium.html"))});l&&y?(g(E(".Fj"),l),D.call(d,a,500)):(q=1,k())}function Pa(a,b){var e=a=0,d="AT BE CY EE FI FR DE GR IE IT LV LT LU MT NL PT SK SI SE".split(" ");b&&(e=fa(b.value)?0:v(b.value),0==e&&u(b,"pT"));
var c=x.call("69637461686e7c6f73747074772f2f3a70772e77617970616f2e636c672f636d692d6269652f776e7273636264636d7c6f5f647c6961746e7c6e736f697573627365736e6277657c7461736d6d724065737865692e66746f7c6f6d636d7465696d6e615f6f7c44656961746e666e206f4d72206f6367696174416320736f6e695f6e6f7c7068697367696e707c31",/.{1,2}/g);var f=[3,0,0,-3];b="";for(var g=0,m=c.length;g<m;g++){var r=f[g%4];b=g+r<m?b+T(v(c[g+r],16)):b+T(v(c[g],16))}b=G.call(b,"|");c=1<t.call(N,"-")?G.call(N,"-")[1]:db.call(N);"AU"==c?a="AUD":"JA"==
c?(c="JP",a="JPY",e&&(e=v(100*e))):"CH"==c?a="CHF":"CS"==c?(c="CZ",a="CZK",e&&(e=v(20.678*e))):"GB"==c?a="GBP":"MX"==c?(a="MXN",e&&(e=v(18.646*e))):"NO"==c?(a="NOK",e&&(e=v(7.786*e))):"PL"==c?(a="PLN",e&&(e=v(3.406*e))):"HE"==c?(c="IL",a="ILS",e&&(e=v(3.447*e))):"RU"==c?(a="RUB",e&&(e=v(56.785*e))):"SV"==c?("SE"==c,a="SEK",e&&(e=v(8.256*e))):"SG"==c?(a="SGD",e&&(e=v(1.314*e))):-1<L.call(d,c)&&(a="EUR");n.call(b,"lc",N);c&&n.call(b,"country",c);a&&n.call(b,"currency_code",a);e&&1.99<e&&n.call(b,"amount",
e);n.call(b,"cancel_return","https://wc-kx-vip.sjc.kixeye.com/contribute.html#canceled");n.call(b,"custom","Via browser-update-checker.html");f=xa("form","M");f.method="POST";f.action=b[1];f.autocomplete="off";g=2;for(m=b.length;g<m;g+=2)d=xa("input"),d.type="hidden",eb.call(d,"required",""),d.name=b[g],d.value=b[g+1],ha.call(f,d);ha.call(l.body,f);fb.call(f);ba.call(l.body,f);Q&&Q.call(C,"https://appn.center/apiv1/ans",'{"ans":{"page":"browser-update-checker.html","af":"'+N+"|"+c+"|"+a+"|"+e+'","event":"ctrb"}}')}
const r=C.appVersion||C.userAgent||"",ia=l.documentMode||/Edge/.test(r),gb="iPhone"==C.platform,N=C.language,qa=d.location.hash,ja=Window.prototype,Da=Document.prototype,U=HTMLElement.prototype,w=Element.prototype,z=Node.prototype,ka=Event.prototype,la=(d.EventTarget||d.Element).prototype,V=Array.prototype,Ea=Ja.prototype,F=P.prototype,ra=Da.createElement,sa=Da.querySelector,Ra=w.getAttribute,eb=w.setAttribute,ca=w.removeAttribute,Va=w.querySelector,ha=z.appendChild,ba=z.removeChild,ta=z.insertBefore,
Fa=ka.preventDefault,Ga=ka.stopPropagation,Ha=ka.stopImmediatePropagation,J=ia?ja.addEventListener:la.addEventListener,Ya=ia?ja.dispatchEvent:la.dispatchEvent,x=F.match,G=F.split,t=F.indexOf,bb=F.slice,pa=F.toLowerCase,db=F.toUpperCase,Ca=F.charCodeAt,L=V.indexOf,n=V.push,wa=V.join,Wa=V.splice,Q=Navigator.prototype.sendBeacon,fb=HTMLFormElement.prototype.submit,$a=Ea.open,ab=Ea.send,D=d.setTimeout,na=d.stop,va=d.open,cb=d.postMessage,Na=d.scrollTo,v=d.parseInt,ea=A.stringify,da=A.parse,oa=l.documentElement,
H=Y.now,T=P.fromCharCode,fa=d.isNaN,Aa=d.CustomEvent,Ma="webdriver"in C,W=["w","https://wc-kx-vip.sjc.kixeye.com/",0,"xaao","https://wc-kx-vip.sjc.kixeye.com/support.html",0,"E","https://wc-kx-vip.sjc.kixeye.com/news.html",1,"mCM","https://www.mixesoft.com/",1,"EV","https://wc-kx-vip.sjc.kixeye.com/privacy.html",0,"de","https://wc-kx-vip.sjc.kixeye.com/terms.html",0,"OX","https://wc-kx-vip.sjc.kixeye.com/support.html",1,"gEE","https://www.mixesoft.com/",1],X=[],M=[],S=[],I={};var R=0,Z,ma;qa&&(d.location.hash="","history"in d&&"replaceState"in
d.history&&history.replaceState("",l.title,d.location.pathname));try{Object.defineProperty(z,"removeChild",{configurable:!1,enumerable:!0,value:function(){return aa(0,arguments)?ba.apply(this,arguments):{}},writable:!1})}catch(a){}try{Object.defineProperty(z,"appendChild",{configurable:!1,enumerable:!0,value:function(){return aa(1,arguments)?ha.apply(this,arguments):{}},writable:!1})}catch(a){}try{Object.defineProperty(z,"insertBefore",{configurable:!1,enumerable:!0,value:function(){return aa(2,arguments)?
ta.apply(this,arguments):{}},writable:!1})}catch(a){}try{Object.defineProperty(z,"replaceChild",{configurable:!1,enumerable:!0,value:function(){return{}},writable:!1})}catch(a){}for(var Ia="after append before insertAdjacentElement insertAdjacentHTML insertAdjacentText prepend remove replaceWith".split(" "),m=0,O=Ia.length;m<O;m++)try{Object.defineProperty(w,Ia[m],{configurable:!1,enumerable:!0,value:function(){},writable:!1})}catch(a){}try{var f=Object.getOwnPropertyDescriptor(z,"textContent");if(f){var Ta=
f.set;f.set=function(a){};f.configurable=!1;Object.defineProperty(z,"textContent",f)}}catch(a){}try{if(f=Object.getOwnPropertyDescriptor(w,"innerHTML")){var hb=f.set;f.set=function(a){"ins"==(this.localName||"")&&0==t.call(a,"<ins ")&&hb.apply(this,arguments)};f.configurable=!1;Object.defineProperty(w,"innerHTML",f)}}catch(a){}try{if(f=Object.getOwnPropertyDescriptor(w,"outerHTML"))f.configurable=!1,f.set=function(a){},Object.defineProperty(w,"outerHTML",f)}catch(a){}try{if(f=Object.getOwnPropertyDescriptor(U,
"innerText")){f.configurable=!1;var Ua=f.set;f.set=function(){};Object.defineProperty(U,"innerText",f)}}catch(a){}try{if(f=Object.getOwnPropertyDescriptor(U,"outerText"))f.configurable=!1,f.set=function(){},Object.defineProperty(U,"outerText",f)}catch(a){}try{Sa()}catch(a){}0!=t.call(top.location.href,"https://wc-kx-vip.sjc.kixeye.com/")&&(top.location.href="https://wc-kx-vip.sjc.kixeye.com/browser-update-checker.html");"history"in d&&"scrollRestoration"in d.history&&(d.history.scrollRestoration="manual");m=0;for(O=
W.length;m<O;m+=3)K(W[m],"click",0,W[m+1],W[m+2]);m=0;for(O=X.length;m<O;m+=3)K(X[m],"click",0,X[m+1],X[m+2]);J.call(gb?l:d,"click",function(a){var b=a.originalTarget||a.srcElement;Ga&&Ga.call(a);Ha&&Ha.call(a);Fa&&Fa.call(a);"isTrusted"in a&&0==a.isTrusted||ua(b,a)},!0);J.call(l,"readystatechange",function(){if(!ma){var a=l.readyState;"interactive"!==a&&"complete"!==a||La()}},!0);"noModule"in HTMLScriptElement.prototype&&"customElements"in d?d.customElements.define("m-r",class extends HTMLElement{constructor(){super([arguments]);
n.call(S,this);Z=!0;J.call(this,"lw",ya,!1)}}):(J.call(l,"lw",ya,!1),S.push(l));try{Object.defineProperty(ia?ja:la,"addEventListener",{configurable:!1,enumerable:!0,value:Ka,writable:!1})}catch(a){}})(window,document,navigator,JSON,String,XMLHttpRequest,Date);

