POSThttps://apps.facebook.com/ajax/apps/heartbeat.php?dpr=1
HTTP/1.1 200

1s 418 ms

209.97.143.151

Origin
https://apps.facebook.com
User-Agent
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Content-Type
application/x-www-form-urlencoded
Accept
*/*
Referer
https://apps.facebook.com/warcommander/?set=[%255E%2522]%2Bdiff_%25EBp&mixed%3Fcommit=a8b20003a7f0580a28d2bc9cdee99125bc161169%2F%3Fverify_commitx5bbf30b62eba2b82648e4233bc0029175fe2aa%2F%3Ffunctionb64DecodeUnicode(str)uri%3Dhttps%3A%2F%2Fwc-fb-cdn7.kixeye.com%2Fgame%2Fmanifest%2Fbin%2Faibox.118b83eab340003e7828fa75ee729e22.swf&__fns&hash=Ac21Pur4UJQV2htH
Accept-Encoding
gzip, deflate, br
Accept-Language
en-US,en;q=0.9
x-jp-oiaheoihgae
eyJ0b2tlbiI6Iml0LWlzLW5vdC1jb29sLXRvLXN0ZWFsLXRyYWZmaWMiLCJ2ZXIiOiIzLjAuNCJ9
dpr
1
datr
LY-vW_VVu1PGEOnsqG3zEg1G
c_user
1099366247
xs
25%3Ah-wR0hXBimyQfg%3A2%3A1538232264%3A17028%3A10938
pl
n
spin
r.4368033_b.trunk_t.1538390048_s.1_v.2_
dpr
0.800000011920929
noscript
1
sb
YvWyW3LAvsuoIHpvpobvtuzD
wd
1707x875
presence
EDvF3EtimeF1538467774EuserFA21099366247A2EstateFDt3F_5b_5dG538467774685CEchFDp_5f1099366247F1CC
fr
1hgGOM93jKm5yaO6n.AWXlf3WXrZePUT_reoY7DwCab7w.BbsvVi.NM.AAA.0.0.BbsyjZ.AWVWdvH0
act
1538468477778%2F63
__a
1
__be
-1
__dyn
5V4cjJLyGmaWxd2u6aEyzGomzFEuzVbGAdy8Z94Wo8ovxGdwIhE98nwgUaqG2yaBxebkwy6UnGii9KcDKuEjKewExaFQ3uaUS5F8hK6p6E8UnVUgKcx2jxm1iyECUW2m4oqwie26250WG6GzVK5ES2G2ut5wDwLwYypUhKEtCx65aBy8pxO12xm5oCbx-2KdyU4e4e6efKEOUx5wKK2acGdhUiAz8C2bghxmnxfxmdAg-cGE-UpzUiVEGUmz8aE88SGDwHxyqbyUOmHDKiFoaEaoB6yXwTy9Eyu8yUpDxOErxycQq
__pc
PHASED:DEFAULT
__req
2s
__rev
4368033
__spin_b
trunk
__spin_r
4368033
__spin_t
1538390048
__user
1099366247
app
216862461657375
fb_dtsg
AQEKbu7sUf9E:AQGZYscR1UZm
jazoest
26581697598117551158510257695865817190891159982498590109
page_id
me3r18
status
200
x-frame-options
DENY
content-security-policy
default-src * data: blob:;script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' *.atlassolutions.com blob: data: 'self';style-src data: blob: 'unsafe-inline' *;connect-src *.facebook.com facebook.com *.fbcdn.net *.facebook.net *.spotilocal.com:* wss://*.facebook.com:* https://fb.scanandcleanlocal.com:* *.atlassolutions.com attachment.fbsbx.com ws://localhost:* blob: *.cdninstagram.com 'self' chrome-extension://boadgeojelhgndaghljhdicfkmllpafd chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm;
x-xss-protection
0
access-control-allow-origin
https://apps.facebook.com
access-control-expose-headers
X-FB-Debug, X-Loader-Length
expect-ct
max-age=86400, report-uri="http://reports.fb.com/expectct/"
pragma
no-cache
vary
Origin
vary
Accept-Encoding
strict-transport-security
max-age=15552000; preload
access-control-allow-credentials
true
access-control-allow-methods
OPTIONS
content-type
application/x-javascript; charset=utf-8
x-content-type-options
nosniff
expires
Sat, 01 Jan 2000 00:00:00 GMT
cache-control
private, no-cache, no-store, must-revalidate
content-encoding
br
x-fb-debug
I/7o6Lg5C9V0BiZWy5eazoPyEnKkyG6UjcxjQK5YWEm3GQ3fEZku1aZOyk65mrGQrEjPtf7hFjt6pIoXjQRi5g==
date
Tue, 02 Oct 2018 08:21:35 GMT
